
package tp4.view;

import Clases.GestorServicio;
import java.awt.Color;


public class Pantalla extends javax.swing.JFrame {


    public Pantalla() {
        initComponents();
        setSize(1010,600);
        setResizable(false);
        setLocationRelativeTo(null);
        
        this.repaint(); 
        GestorServicio gestor = new GestorServicio(this);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_servicios = new javax.swing.JTable();
        tabbedPaneCustom1 = new tp4.view.tabbedPane.TabbedPaneCustom();
        jPanel1 = new javax.swing.JPanel();
        media_atencion_combustible = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        media_llegada_combustible = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        media_llegada_lavado = new javax.swing.JTextField();
        media_atencion_lavado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        media_llegada_mantenimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        media_atencion_mantenimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        media_llegada_caja = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        media_atencion_caja = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_simular = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nro_simulaciones = new javax.swing.JTextField();
        hasta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        desde = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(152, 202, 203));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setMinimumSize(new java.awt.Dimension(1500, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(1010, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(241, 233, 220));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 233, 220));
        jLabel1.setText("ESTACIÓN DE SERVICIO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        tabla_servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reloj", "Ll. Combustible ", "Ll. Lavado", "Ll. Mantenimiento", "Ll. Caja", "At. Combustible 1", "At. Combustible 2", "At. Combustible 3", "At. Combustible 4", "At. lavado 1", "At. lavado 2", "At. Mantenimiento 1", "At. Mantenimiento 2", "At. caja 1", "At. caja 2", "S1 Estado", "S1 Cola", "S2 Estado", "S2 Cola", "S3 Estado", "S3 Cola", "S4 Estado", "S4 Cola"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_servicios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla_servicios.setDragEnabled(true);
        tabla_servicios.setMaximumSize(new java.awt.Dimension(800, 400));
        jScrollPane4.setViewportView(tabla_servicios);
        if (tabla_servicios.getColumnModel().getColumnCount() > 0) {
            tabla_servicios.getColumnModel().getColumn(1).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(2).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(4).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(5).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(6).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(7).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(8).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(9).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(10).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(11).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(12).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(13).setPreferredWidth(120);
            tabla_servicios.getColumnModel().getColumn(14).setPreferredWidth(120);
        }

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 950, 280));

        tabbedPaneCustom1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(0, 102, 102));

        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        media_atencion_combustible.setText("3");
        media_atencion_combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media_atencion_combustibleActionPerformed(evt);
            }
        });
        jPanel1.add(media_atencion_combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("FIN ATENCIÓN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("LLEGADA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        media_llegada_combustible.setText("2");
        media_llegada_combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media_llegada_combustibleActionPerformed(evt);
            }
        });
        jPanel1.add(media_llegada_combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp4/images/icons8-gasolinera-50.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        tabbedPaneCustom1.addTab("Combustible", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("LLEGADA:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        media_llegada_lavado.setText("4");
        jPanel2.add(media_llegada_lavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, -1));

        media_atencion_lavado.setText("6");
        jPanel2.add(media_atencion_lavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp4/images/icons8-lavado-automático-de-vehículos-50.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 60));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("FIN ATENCIÓN:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        tabbedPaneCustom1.addTab("Lavado", jPanel2);

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 66));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("LLEGADA:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        media_llegada_mantenimiento.setText("6");
        jPanel4.add(media_llegada_mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("FIN ATENCIÓN:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        media_atencion_mantenimiento.setText("12");
        jPanel4.add(media_atencion_mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp4/images/icons8-servicio-de-coche-64.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 60));

        tabbedPaneCustom1.addTab("Mantenimiento", jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(500, 66));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("LLEGADA:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        media_llegada_caja.setText("1.5");
        jPanel5.add(media_llegada_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("FIN ATENCIÓN:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        media_atencion_caja.setText("4");
        jPanel5.add(media_atencion_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp4/images/icons8-caja-registradora-50.png"))); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 60));

        tabbedPaneCustom1.addTab("Caja", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_simular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_simular.setText("Generar simulación");
        jPanel6.add(btn_simular, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 170, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Nro simulaciones:");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setText("Hasta:");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 20));

        nro_simulaciones.setText("300");
        nro_simulaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nro_simulacionesActionPerformed(evt);
            }
        });
        jPanel6.add(nro_simulaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, -1));

        hasta.setText("100");
        jPanel6.add(hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setText("Desde:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 20));

        desde.setText("1");
        jPanel6.add(desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 110, -1));

        tabbedPaneCustom1.addTab("Simular", jPanel6);

        jPanel3.add(tabbedPaneCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 650, 150));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void media_atencion_combustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media_atencion_combustibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_media_atencion_combustibleActionPerformed

    private void nro_simulacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nro_simulacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nro_simulacionesActionPerformed

    private void media_llegada_combustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media_llegada_combustibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_media_llegada_combustibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_simular;
    public javax.swing.JTextField desde;
    public javax.swing.JTextField hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextField media_atencion_caja;
    public javax.swing.JTextField media_atencion_combustible;
    public javax.swing.JTextField media_atencion_lavado;
    public javax.swing.JTextField media_atencion_mantenimiento;
    public javax.swing.JTextField media_llegada_caja;
    public javax.swing.JTextField media_llegada_combustible;
    public javax.swing.JTextField media_llegada_lavado;
    public javax.swing.JTextField media_llegada_mantenimiento;
    public javax.swing.JTextField nro_simulaciones;
    private tp4.view.tabbedPane.TabbedPaneCustom tabbedPaneCustom1;
    public javax.swing.JTable tabla_servicios;
    // End of variables declaration//GEN-END:variables
}
